### PR TITLE
use global transformation for distance to surface

### LINKED ISSUE #644: investigate distance_to_surface for volumes with complex positioning
the calculation of the transform of the global hit coordinates to the local object frame did not properly take into account the translations of the mother volume(s). This leads to wildly wrong values.

### PR DESCRIPTION
**Pull request by ManuelHu**
the updated distance validation tests should now also cover this case and fail if not implemented correctly.

fixes #644

### CODE REVIEW

File: src/RMGNavigationTools.cc [hunk 1]
```diff
@@ -268,4 +268,14 @@ std::vector<RMGNavigationTools::VolumeTreeEntry> RMGNavigationTools::FindGlobalP
   return trees;
 }
 
+RMGNavigationTools::VolumeTreeEntry RMGNavigationTools::FindGlobalPositionCached(
```
Comment (EricMEsch) [inline src/RMGNavigationTools.cc]: Why is the function name `cached`? It just re-calculates the distance every time right?

Comment (ManuelHu) [reply src/RMGNavigationTools.cc]: I think you commented on an outdated commit? in the latest version it is not called `Cached` any more...
